events { worker_connections 256; }

http {
    server_tokens off;

    server {
        listen 80;

        location /health { proxy_pass http://backend:8000/health; }
        location /auth/  { proxy_pass http://backend:8000/auth/; }
        location /api/   { proxy_pass http://backend:8000/api/; }
        location /       { proxy_pass http://mviewer:80/; }
    }
}
